### PR TITLE
Custom termination date

### PR DESCRIPTION
**Pull request by alexaunter**
Added ability to terminate contract not "as of now" but in any specific moment in the future.
Motivation: for legal implications, we need to be precise when terminating lockups.

If the termination timestamp is in the future, the schedule will be truncated in that moment in the future
If the termination timestamp is in the past - current timestamp will be used for schedule truncation

### CODE REVIEW

**Comment by alexaunter** [comment]
FYI @frol: updated code to fail when terminate is called with past timestamp.

**Comment by alexaunter** [comment]
@evgenykuzyakov , is there anything stopping us from splitting unit tests into separate files?
I think it will make working with multiple parallel merge requests easier (by reducing number of conflicts, currently I just append unit tests to the end of the file).
Is there any policy on unit tests?
Do you think it's worth the effort?

**Review by frol — APPROVED** [review]
LGTM

**Comment by frol** [comment]
@evgenykuzyakov This is useful for the legal team since rarely one want to submit a termination transaction exactly at 00:00 of a certain day.

**Review by evgenykuzyakov — APPROVED** [review]

**Pull request merged**
